### PR TITLE
Use do...catch for JSON parsing instead of try!

### LINKED ISSUE #10: Possible Crash in WidgetViewController due to force unwrapping (try!)
# Potential App Crash in WidgetViewController due to unsafe force unwrap (try!)

### Description
I found a possible crash in the iOS SDK that causes the app to crash (Local DoS). The issue is located in the `WidgetViewController` class inside the `userContentController` method.

The code uses the `try!` operator to decode JSON messages. If the JavaScript bridge sends invalid data or the API structure changes, the application crashes immediately for the user.

### Location
* **File:** `FriendlyCaptcha.swift`
* **Line:** [323](https://github.com/FriendlyCaptcha/friendly-captcha-ios/blob/main/FriendlyCaptcha/Classes/FriendlyCaptcha.swift#L323)
* **Code:**
```swift
let message = try! JSONDecoder().decode(FriendlyCaptchaMessage.self, from: data)
```

### Impact
If the server response is unexpected or the JSON data is corrupted, the mobile app will crash. This makes the SDK integration unstable for production environments.

### Suggested Fix
Please replace the unsafe `try!` with a proper `do-catch` block to handle errors safely.

**Example of safer code:**
```swift
do {
    let message = try JSONDecoder().decode(FriendlyCaptchaMessage.self, from: data)
    // process the message
} catch {
    print("FriendlyCaptcha SDK Error: Failed to decode message: \(error)")
    // handle the error without crashing the app
}
```

Thank you for your library. I hope you will fix this potential crash very soon!

### PR DESCRIPTION
**Pull request by greenberga**
Avoids `try!` which can crash an application. Opts instead for `do...catch`, which will print an error message but continue running. Our tests should still catch any drift between the JavaScript SDK JSON objects and the shape of the Swift classes into which they are decoded.

Closes #10

### CODE REVIEW

File: FriendlyCaptcha/Classes/FriendlyCaptcha.swift [hunk 1]
```diff
@@ -318,21 +318,25 @@ class WidgetViewController: UIViewController, WKScriptMessageHandler, WKNavigati
...
+                    let message = try JSONDecoder().decode(WidgetExpireEvent.self, from: jsonData)
+                    handleExpire(message)
+                case "statechange":
+                    let message = try JSONDecoder().decode(WidgetStateChangeEvent.self, from: jsonData)
+                    handleStateChange(message)
+                default:
+                    print("FriendlyCaptcha: Unknown message type", body)
+                }
+            } catch {
+                print("FriendlyCaptcha: Failed to decode '\(type)' event: \(error)")
```
Comment (ivan-gaydamakin) [inline FriendlyCaptcha/Classes/FriendlyCaptcha.swift:345]: please add here any closure to catch that bug on app side

**Review by gzuidhof — APPROVED** [review]

File: FriendlyCaptcha/Classes/FriendlyCaptcha.swift (hunk 1 above)
Comment (greenberga) [reply FriendlyCaptcha/Classes/FriendlyCaptcha.swift:345]: We changed it to use the existing `onError` callback
